# platform :ios, 12.0

target 'Adobe AEP Sample' do
  use_frameworks!

  # Pods for Adobe AEP Sample
  pod 'AEPLifecycle'
  pod 'AEPSignal'
  pod 'AEPMobileServices'
  pod 'AEPAnalytics' 
  pod 'AppsFlyerAdobeAEPExtension-qa','6.14.4-rc4'
  pod 'AEPCore'

end
